// Angular-client/src/app/core/ui/header/header.component.ts
import { Component } from "@angular/core";
import { AuthService } from "../../../auth/services/auth.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.css"]
})
export class HeaderComponent {
  constructor(private authService: AuthService, private router: Router) {}

  onLogout() {
    this.authService.logout();
    this.router.navigate(["/"]);
  }
}

<nav class="navbar navbar-fixed-top navbar-default" style="padding: 0px;">
  <div class="container-fluid" style="padding: 0px;">
    <div
      class="navbar-header"
      style="background-color: rgb(57, 121, 218); width: 150px; text-align: center;"
    >
      <a routerLink="/" class="navbar-brand">&nbsp;Ng-Client</a>
    </div>

    <ng-template [ngIf]="authService.isAuthenticated()">
      <ul class="nav navbar-nav" style="margin-left: 10px; margin-top: 5px">
        <li>
          <input class="form-control search" type="text" placeholder="Search" />
        </li>
      </ul>
    </ng-template>

    <ul class="nav navbar-nav navbar-right" style="margin-right:15px;">
      <ng-template [ngIf]="!authService.isAuthenticated()">
        <li>
          <a routerLink="/user/signup"
            ><i class="fa fa-user" aria-hidden="true"></i>&nbsp;Sign Up</a
          >
        </li>
        <li>
          <a routerLink="/auth/signin"
            ><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Sign In</a
          >
        </li>
      </ng-template>

      <ng-template [ngIf]="authService.isAuthenticated()">
        <li dropdown show>
          <a dropdownToggle role="button"
            >{{ authService.userName }}&nbsp;<span class="caret"></span
          ></a>
          <ul *dropdownMenu class="dropdown-menu" role="menu">
            <li><a routerLink="/user/updateProfile">Update Profile</a></li>
            <li><a routerLink="/user/uploadPicture">Upload Picture</a></li>
            <li><a routerLink="/user/changePassword">Change Password</a></li>
            <li>
              <a
                style="cursor: pointer;"
                (click)="onLogout()"
                *ngIf="authService.isAuthenticated()"
                >Logout</a
              >
            </li>
          </ul>
        </li>
        <li style="margin-right: 20px">
          <img
            class="avatar"
            [src]="authService.imageToShow"
            *ngIf="authService.imageToShow"
          />
        </li>
      </ng-template>
    </ul>
  </div>
</nav>

// React-client/src/shared/header/header.js
import React from "react";
import { Link } from "react-router-dom";
import { connect } from "react-redux";
import { NavDropdown, MenuItem } from "react-bootstrap";
import { withRouter } from "react-router-dom";
import SideBar from "../sidebar/sidebar";
import SubHeader from "./subheader";

class Header extends React.Component {
  handleLogout = () => {
    this.props.authenticate();
    this.props.history.push("/");
  };

  handleSelect = eventKey => {
    if (eventKey === "1") {
      this.props.history.push("/updateprofile");
    } else if (eventKey === "2") {
      this.props.history.push("/uploadpicture");
    } else if (eventKey === "3") {
      this.props.history.push("/changepassword");
    } else if (eventKey === "4") {
      this.handleLogout();
    }
  };

  render() {
    let view = null;
    if (this.props.isAuthenticated === true) {
      view = (
        <ul
          className="nav navbar-nav navbar-right"
          style={{ marginRight: "15px" }}
        >
          <NavDropdown
            eventKey="0"
            title={this.props.userName}
            id="nav-dropdown"
            onSelect={k => this.handleSelect(k)}
          >
            <MenuItem eventKey="1">Update Profile</MenuItem>
            <MenuItem eventKey="2">Upload Picture</MenuItem>
            <MenuItem eventKey="3">Change Password</MenuItem>
            <MenuItem eventKey="4">Logout</MenuItem>
          </NavDropdown>
        </ul>
      );
    } else {
      view = (
        <ul
          className="nav navbar-nav navbar-right"
          style={{ marginRight: "15px" }}
        >
          <li className="nav-item">
            <Link className="nav-link" to="/signup">
              <i className="fa fa-user" aria-hidden="true" />
              &nbsp;Sign Up
            </Link>
          </li>
          <li className="nav-item">
            <Link className="nav-link" to="/signin">
              <i className="fa fa-sign-in" aria-hidden="true" />
              &nbsp; Sign In
            </Link>
          </li>
        </ul>
      );
    }

    return (
      <React.Fragment>
        <div className="row">
          <nav
            className="navbar navbar-fixed-top navbar-default"
            style={{ padding: "0px" }}
          >
            <div className="container-fluid" style={{ padding: "0px" }}>
              <div
                className="navbar-header"
                style={{
                  backgroundColor: "rgb(57, 121, 218)",
                  width: "150px",
                  textAlign: "center"
                }}
              >
                <Link to="/" className="navbar-brand">
                  &nbsp;React-Client
                </Link>
              </div>
              <div className="collapse navbar-collapse">{view}</div>
            </div>
          </nav>
        </div>
        <div className="row">
          <SideBar />
        </div>
      </React.Fragment>
    );
  }
}

const mapStateToProps = state => {
  return {
    userName: state.userName,
    token: state.token,
    imageToShow: state.imageToShow,
    isAuthenticated: state.isAuthenticated
  };
};

const mapDispatcherToProps = dispatch => {
  return {
    authenticate: () => {
      dispatch({ type: "logout" });
    }
  };
};

export default withRouter(
  connect(
    mapStateToProps,
    mapDispatcherToProps
  )(Header)
);
