// Angular-client/src/app/user/changepassword/changepassword.component.ts
import { Component, OnInit } from "@angular/core";
import { UserService } from "../user.service";
import { Router } from "@angular/router";
import { NgForm } from "@angular/forms";
import { FlashService } from "src/app/core/services/flash.service";

@Component({
  selector: "app-changepassword",
  templateUrl: "./changepassword.component.html",
  styleUrls: ["./changepassword.component.css"]
})
export class ChangepasswordComponent implements OnInit {
  default = {
    oldpassword: "",
    password: "",
    confirmpassword: ""
  };
  submitError: string = "";
  submitSuccess: string = "";

  constructor(
    private userService: UserService,
    private router: Router,
    private flashService: FlashService
  ) {}

  ngOnInit() {}

  onSubmit(form: NgForm) {
    if (form.valid) {
      this.userService.changePassword(form.value).subscribe(
        (data: any) => {
          this.submitError = "";
          this.flashService.successMessage(data["message"]);
          //this.submitSuccess = data["message"];
        },
        error => {
          if (error.error.hasOwnProperty("message")) {
            this.submitError = error.error.message;
            this.submitSuccess = "";
          } else {
            this.submitError = "Unknown Error. Please contact administrator.";
            this.submitSuccess = "";
          }
        }
      );
    }
  }
}

<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
    <div *ngIf="submitSuccess != ''" class="alert alert-success">
      {{ submitSuccess }}
    </div>
    <div *ngIf="submitError != ''" class="alert alert-danger">
      {{ submitError }}
    </div>
    <form (ngSubmit)="onSubmit(f)" #f="ngForm">
      <div class="form-group">
        <label for="password">Old Password</label>
        <input
          type="password"
          id="oldpassword"
          name="oldpassword"
          [ngModel]="default.oldpassword"
          #oldpassword="ngModel"
          required
          class="form-control"
        />
        <form-control-error
          [control]="oldpassword"
          [label]="'Old Password'"
        ></form-control-error>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          [ngModel]="default.password"
          #password="ngModel"
          required
          minlength="8"
          class="form-control"
        />
        <form-control-error
          [control]="password"
          [label]="'Password'"
          lengthMsg="must be at least 8 characters"
        ></form-control-error>
      </div>
      <div class="form-group">
        <label for="password">Confirm Password</label>
        <input
          type="password"
          id="confirmpassword"
          name="confirmpassword"
          [ngModel]="default.confirmpassword"
          #confirmpassword="ngModel"
          required
          minlength="8"
          class="form-control"
        />
        <form-control-error
          [control]="confirmpassword"
          [label]="'Confirm Password'"
          lengthMsg="must be at least 8 characters"
        ></form-control-error>
      </div>
      <button class="btn btn-primary" type="submit">Update</button>&nbsp;
    </form>
  </div>
</div>

// React-client/src/user/changepassword/changepassword.js
import React from "react";
import FormControlError from "../../core/forms/formcontrollerror";
import handleChange from "../../core/forms/handlechange";
import handleSubmit from "../../core/forms/handleSubmit";
import api from "../../core/service/api";

class ChangePassword extends React.Component {
  state = {
    form: {
      oldpassword: {
        value: "12345678",
        validation: { required: true },
        validationMsg: "",
        label: "Old Password"
      },
      password: {
        value: "12345678",
        validation: { required: true },
        validationMsg: "",
        label: "Password"
      },
      confirmpassword: {
        value: "12345678",
        validation: { required: true },
        validationMsg: "",
        label: "Confirm Password"
      }
    },
    submitStatus: "",
    submitError: "",
    submitSuccess: ""
  };

  handleChange = event => {
    this.setState({ form: handleChange(event, this.state.form) });
  };

  handleSubmit = event => {
    this.setState(
      { form: handleSubmit(event, { ...this.state.form }) },
      function() {
        if (this.state.form.isValid === true) {
          let formData = {};
          for (let formElement in this.state.form) {
            if (formElement !== "isValid" && formElement !== "isSubmitted") {
              formData[formElement] = this.state.form[formElement].value;
            }
          }
          this.callAPI("/user/changePassword", formData);
        }
      }
    );
    event.preventDefault();
  };

  callAPI = (url, data) => {
    api
      .post(url, data)
      .then(response => {
        this.setState({
          submitError: "",
          submitSuccess: response.data.message
        });
      })
      .catch(error => {
        if (error.response.status === 401) {
          this.setState({
            submitError: error.response.data.message,
            submitSuccess: ""
          });
          //console.log(error.response.data);
        }
      });
  };

  render() {
    let view = null;
    view = (
      <div className="row">
        <div className="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2  ">
          <FormControlError validationMsg={this.state.submitError} />
          <FormControlError validationMsg={this.state.submitSuccess} />
          <div>
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label htmlFor="password">Old Password</label>
                <input
                  type="oldpassword"
                  id="oldpassword"
                  name="oldpassword"
                  value={this.state.form.oldpassword.value}
                  onChange={this.handleChange}
                  className="form-control"
                />
                <FormControlError
                  validationMsg={this.state.form.password.validationMsg}
                />
              </div>
              <div className="form-group">
                <label htmlFor="password">Password</label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={this.state.form.password.value}
                  onChange={this.handleChange}
                  className="form-control"
                />
                <FormControlError
                  validationMsg={this.state.form.password.validationMsg}
                />
              </div>
              <div className="form-group">
                <label htmlFor="password">Confirm Password</label>
                <input
                  type="password"
                  id="confirmpassword"
                  name="confirmpassword"
                  value={this.state.form.confirmpassword.value}
                  onChange={this.handleChange}
                  className="form-control"
                />
                <FormControlError
                  validationMsg={this.state.form.confirmpassword.validationMsg}
                />
              </div>
              <button className="btn btn-primary" type="submit">
                Change
              </button>
            </form>
          </div>
        </div>
      </div>
    );
    return <div>{view}</div>;
  }
}

export default ChangePassword;
