// React-client/src/other/socket/socket.js
import React, { Component } from "react";
import { Button } from "react-bootstrap";
import socketService from "./socket.service";

class SocketSample extends Component {
  state = {
    serverMessage: "",
    message: ""
  };

  handleChange = event => {
    this.setState({ message: event.target.value });
  };

  sendMessage = () => {
    socketService.initSocket();
    socketService.onMessage("eventFromServer").subscribe(data => {
      this.setState({ serverMessage: data });
      socketService.disconnectSocket();
    });
    socketService.send("eventFromClient", this.state.message);
  };

  render() {
    return (
      <div>
        <label for="message">Message: </label>
        <input id="message" type="text" onChange={this.handleChange} />
        &nbsp;
        <Button onClick={this.sendMessage} className="btn btn-primary">
          Send Message
        </Button>
        <br />
        Message received from server: {this.state.serverMessage}
      </div>
    );
  }
}

export default SocketSample;

// Angular-client/src/app/other/socket/socket.component.ts
import { Component, OnInit } from "@angular/core";
import { SocketIOService } from "./socketio.service";

@Component({
  selector: "app-socket",
  templateUrl: "./socket.component.html",
  styleUrls: ["./socket.component.css"]
})
export class SocketComponent implements OnInit {
  message: string;
  serverMessage: string;
  constructor(private socketService: SocketIOService) {}

  ngOnInit() {}

  sendMessge() {
    this.socketService.initSocket();
    this.socketService.onMessage("eventFromServer").subscribe(data => {
      this.serverMessage = data;
      this.socketService.disconnectSocket();
    });
    this.socketService.send("eventFromClient", this.message);
  }
}

<p>
  <label for="message">Message: </label
  ><input id="message" type="text" [(ngModel)]="message" />&nbsp;
  <Button (click)="sendMessge()" class="btn btn-primary">Send Message</Button>
  <br />
  Message received from server: {{ serverMessage }}
</p>
