// Angular-client/src/app/user/uploadpicture/uploadpicture.component.ts
import { Component, OnInit } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { Router } from "@angular/router";
import { routerNgProbeToken } from "@angular/router/src/router_module";
import { AuthService } from "src/app/auth/auth.service";
import { ApiService } from "src/app/core/services/api.service";
import { NgxSpinnerService } from "ngx-spinner";

@Component({
  selector: "app-uploadpicture",
  templateUrl: "./uploadpicture.component.html",
  styleUrls: ["./uploadpicture.component.css"]
})
export class UploadpictureComponent implements OnInit {
  selectedFiles: File[];
  constructor(
    private apiService: ApiService,
    private router: Router,
    private authService: AuthService,
    private spinner: NgxSpinnerService
  ) {}

  ngOnInit() {}

  onSubmit(form) {
    const formData = new FormData();
    for (const file of this.selectedFiles) {
      formData.append("files", file);
    }
    this.spinner.show();
    this.apiService.uploadFile("/user/uploadPicture", formData).subscribe(
      success => {
        this.authService.loadPicture();
        this.router.navigate(["/"]);
        this.spinner.hide();
      },
      error => {
        this.spinner.hide();
        console.log(error);
      }
    );
  }
}

<form (ngSubmit)="onSubmit(f)" #f="ngForm">
  <div class="form-group">
    <label for="avatar">Select Picture</label>
    <input
      #fileSelect
      type="file"
      (change)="selectedFiles = fileSelect.files"
    />
  </div>
  <button [disabled]="!selectedFiles" type="submit" class="btn btn-primary">
    Submit
  </button>
</form>

// React-client/src/user/uploadpicture/uploadpicture.js
import React from "react";
import api from "../../core/service/api";

class UploadPicture extends React.Component {
  state = { selectedFile: null };

  fileChangedHandler = event => {
    //this.setState({ file: URL.createObjectURL(event.target.files[0]) });
    this.setState({ selectedFile: event.target.files[0] });
  };

  uploadHandler = () => {
    const formData = new FormData();
    formData.append("files", this.state.selectedFile);

    api.post("/user/uploadPicture", formData).then(
      success => {
        this.props.history.push("/");
      },
      error => {
        console.log(error);
      }
    );
  };

  render() {
    return (
      <form>
        <div className="form-group">
          <label>Select Picture</label>
          <input type="file" onChange={this.fileChangedHandler} />
        </div>
        <button
          type="button"
          className="btn btn-primary"
          onClick={this.uploadHandler}
        >
          Submit
        </button>
      </form>
    );
  }
}

export default UploadPicture;
