// React-client/src/auth/signin/signin.js
import React from "react";
import FormControlError from "../../core/forms/formcontrollerror";
import handleChange from "../../core/forms/handlechange";
import handleSubmit from "../../core/forms/handleSubmit";
import api from "../../core/service/api";
import { connect } from "react-redux";

class SignIn extends React.Component {
  state = {
    form: {
      email: {
        value: "bhavesh1974@gmail.com",
        validation: { required: true, isEmail: true },
        validationMsg: "",
        label: "Email"
      },
      password: {
        value: "12345678",
        validation: { required: true },
        validationMsg: "",
        label: "Password"
      }
    },
    isValid: "",
    isSubmitted: "",
    signInError: "",
    source: null
  };

  handleChange = event => {
    this.setState({ form: handleChange(event, this.state.form) });
  };

  handleSubmit = event => {
    this.setState(
      { form: handleSubmit(event, { ...this.state.form }) },
      function() {
        if (this.state.form.isValid === true) {
          let formData = {};
          for (let formElement in this.state.form) {
            if (formElement !== "isValid" && formElement !== "isSubmitted") {
              formData[formElement] = this.state.form[formElement].value;
            }
          }
          this.callAPI("/auth/signin", formData);
        }
      }
    );
    event.preventDefault();
  };

  callAPI = (url, data) => {
    api
      .post(url, data)
      .then(response => {
        this.props.authenticate(response.data);
        this.props.history.push("/");
      })
      .catch(error => {
        if (error.response) {
          if (error.response.status === 401) {
            this.setState({
              signInError: error.response.data.message
            });
          }
        } else {
          this.setState({
            signInError: "Unknown Error"
          });
        }
      });
  };

  render() {
    return (
      <div className="row">
        <div className="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2  ">
          <FormControlError validationMsg={this.state.signInError} />
          <div>
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label htmlFor="email">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={this.state.form.email.value}
                  onChange={this.handleChange}
                  className="form-control"
                />
                <FormControlError
                  validationMsg={this.state.form.email.validationMsg}
                />
              </div>
              <div className="form-group">
                <label htmlFor="password">Password</label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={this.state.form.password.value}
                  onChange={this.handleChange}
                  className="form-control"
                />
                <FormControlError
                  validationMsg={this.state.form.password.validationMsg}
                />
              </div>
              <button className="btn btn-primary" type="submit">
                Sign In
              </button>
            </form>
          </div>
        </div>
      </div>
    );
  }
}

const mapStateToProps = state => {
  return {
    userName: state.userName,
    token: state.token,
    isAuthenticated: state.isAuthenticated
  };
};

const mapDispatcherToProps = dispatch => {
  return {
    authenticate: data => {
      dispatch({ type: "signin", userName: data.userName, token: data.token });
    },
    setPicture: data => {
      dispatch({ type: "setpicture", picture: data });
    }
  };
};

export default connect(
  mapStateToProps,
  mapDispatcherToProps
)(SignIn);

// Angular-client/src/app/auth/signin/signin.component.ts
import { Component, OnInit } from "@angular/core";
import { NgForm } from "@angular/forms";

import { AuthService } from "../auth.service";
import { Router } from "@angular/router";
import { NgxSpinnerService } from "ngx-spinner";
import { ApiService } from "src/app/core/services/api.service";

@Component({
  selector: "app-signin",
  templateUrl: "./signin.component.html",
  styleUrls: ["./signin.component.css"]
})
export class SigninComponent implements OnInit {
  signinError: string = "";
  imageToShow: any;
  constructor(
    private authService: AuthService,
    private router: Router,
    private spinner: NgxSpinnerService
  ) {}

  ngOnInit() {}

  onSignin(form: NgForm) {
    if (form.valid) {
      this.spinner.show();
      this.authService.signinUser(form.value).subscribe(
        (data: any) => {
          this.spinner.hide();
          this.authService.setToken(data.token);
          this.authService.setUserName(data.userName);
          this.authService.loadPicture();
          this.router.navigate(["/"]);
        },
        error => {
          this.spinner.hide();
          if (error.error.hasOwnProperty("message")) {
            this.signinError = error.error.message;
          } else {
            this.signinError = "Unknown Error. Please contact administrator.";
          }
        }
      );
    }
  }
}

<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
    <div *ngIf="signinError != ''" class="alert alert-danger">
      {{ signinError }}
    </div>
    <form (ngSubmit)="onSignin(f)" #f="ngForm">
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="email"
          id="email"
          name="email"
          ngModel="bhavesh1974@gmail.com"
          #email="ngModel"
          required
          class="form-control"
        />
        <form-control-error label="Email" [control]="email">
        </form-control-error>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          ngModel="12345678"
          #password="ngModel"
          required
          class="form-control"
        />
        <form-control-error label="Password" [control]="password">
        </form-control-error>
      </div>
      <button class="btn btn-primary" type="submit">Sign In</button>
    </form>
  </div>
</div>
